sudo: required
services:
- docker
git:
  depth: false
env:
  global:
    secure: RftkhfFw+9LpTLbU648C76UlS9bf3+QMyFQol5/MoSmwhjHv5km12WP2Qeziwcu4I0ZeRfCP7guFl9uYe+eNOvEmsZI0fgN0nX2vvFYSvWB4qsNN6ocVZ0UT7xXKyBUBhpR7NrHm6Lmz5ILFdlZ7OBZXYO/dXBxKaCCo40xdrT6JpCfHfMe5VjT5yHkKmGrudSdEBVCGtg4aWc2bNKw84RaaSZAjrXBki4klGJUBo4TSLPyzfqNr2N7eGE4ovxPQx3ePMxFtBGgeKVUysYIsyN97Q1dRbvtpdgsDTaNoK2WNlfd1h8yEOZ/GBmkbrORAmUPt1iTyNkw/hAQOUdDL+4wPvhoHWZo8qkOzcAzVNM5ilkwze0/4hQ/lhaWLlJ7XN3os/DelISJCPsSq20upDOw/G2eb7BEQMu9+2JuwCvTZguL9WD8DE/kONSSj/LYCfJpIeWNWjC+EWmy5HLrLmiZj6urZBIQQDxHpHekFMg1FwO6eiXvzVnjcsv96Sx+3Xzj24UyN/YlH+pic1dnzsMWYlQMCkr32kDuMxkNnfF7LG/OhtaNlLFtSPr+xaqqktCdTfOclQTcE3RmMocc92V1OrwNnfa/CIoFxllFgyGSP1P81a/sU9xaWGav/m27Ob8deWlTkQ2BDjGMonS/FSH8tCA7qbqJDplrERAjrbY8=
stages:
- stable package
- nightly package
jobs:
  include:
  - stage: stable package
    if: branch != master OR tag =~ ^.*$
    env: CACHE_NAME=stretch_package
    name: Stable package Debian 9
    script: &build_stretch
    - docker build -t yeti-lb-9 -f ./ci/build_stretch.Dockerfile .
    - docker run --name yeti-lb-9 yeti-lb-9 && docker commit yeti-lb-9 yeti-lb-9:built
    deploy:
      skip_cleanup: true
      provider: script
      script: docker run --name yeti-lb-9-deploy yeti-lb-9:built ci/deploy.sh "$API_ENDPOINT" stretch "${TRAVIS_TAG%.*}" main /build/*.deb
      on:
        tags: true
        condition: "$TRAVIS_TAG != *-master*"
        repo: yeti-switch/yeti-lb
  - stage: stable package
    if: branch != master OR tag =~ ^.*$
    env: CACHE_NAME=buster_package
    name: Stable package Debian 10
    script: &build_buster
    - docker build -t yeti-lb-10 -f ./ci/build_buster.Dockerfile .
    - docker run --name yeti-lb-10 yeti-lb-10 && docker commit yeti-lb-10 yeti-lb-10:built
    deploy:
      skip_cleanup: true
      provider: script
      script: docker run --name yeti-lb-10-deploy yeti-lb-10:built ci/deploy.sh "$API_ENDPOINT" buster "${TRAVIS_TAG%.*}" main /build/*.deb
      on:
        tags: true
        condition: "$TRAVIS_TAG != *-master*"
        repo: yeti-switch/yeti-lb

  - stage: nightly package
    if: branch = master
    env: CACHE_NAME=stretch_package
    name: Nightly package Debian 9
    script: *build_stretch
    deploy:
      skip_cleanup: true
      provider: script
      script: docker run --name yeti-lb-9-deploy yeti-lb-9:built ci/deploy.sh "$API_ENDPOINT" stretch nightly main /build/*.deb
      on:
        all_branches: true
        repo: yeti-switch/yeti-lb

  - stage: nightly package
    if: branch = master
    env: CACHE_NAME=buster_package
    name: Nightly package Debian 10
    script: *build_buster
    deploy:
      skip_cleanup: true
      provider: script
      script: docker run --name yeti-lb-10-deploy yeti-lb-10:built ci/deploy.sh "$API_ENDPOINT" buster nightly main /build/*.deb
      on:
        all_branches: true
        repo: yeti-switch/yeti-lb
